---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mern-app
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: martinsops
        image: martinsops/frontend:1.0
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://backend:8080"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mern-app
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 3000